### ISSUE TITLE
Fix: Graph representation in the website

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Sulagna-Dutta-Roy/Covid19-website#26]
Use Javascript library or use Chart.Js for the graph. Anyone have the experience with regular graph contributing chart can work on this.
Also anyone wants to add covid-19 affected Increment Decrement counter. whenever user open this website the counter will show the total number of patients affected till now.

**Comment by Akanksha-Sen** [comment]
Please assign me this. I want to add graph using js library.

**Comment by coderSuren** [comment]
@Sulagna-Dutta-Roy Is this issue still open? If so can I work on it?

**Comment by Sulagna-Dutta-Roy** [comment]
@Akanksha-Sen any update on this ??? Then I will assign @coderSuren

**Comment by Akanksha-Sen** [comment]
I'm unable to work on it due to some personal issues. Please assign it to the other person.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay.

**Comment by Sulagna-Dutta-Roy** [comment]
Assigned to you @coderSuren
