### ISSUE TITLE
Fix: enhance the details section

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Sulagna-Dutta-Roy/Covid19-website#29]
- Customized the "Details" button. 
- Also add the html link into it. User will click the button and the another page will open where all the details will be filled about covid-19.

**Comment by Bhavesh-Rawat** [comment]
May, I work on this issue ?

**Comment by Sulagna-Dutta-Roy** [comment]
Design one page for the details button and link to it.
