### ISSUE TITLE
Want to work on steps to protect yourself section.

### ISSUE THREAD

**Issue by vedsom** [Sulagna-Dutta-Roy/Covid19-website#35]
I have observed that there is no active link for wash hand ,wear mask, get vaccinated learn more button. I want to add pages related to that topics with aa great CSS styles. Kindly assign me this task under HSOC-22. Thanks.

![Covid-19 Tracker Website - Google Chrome 21-07-2022 23_31_53](https://user-images.githubusercontent.com/96954912/180284149-f0096552-47d1-4529-9ecb-751685c12a29.png)

**Comment by vedsom** [comment]
@Sulagna-Dutta-Roy can you assign me to solve this issue?

**Comment by Sulagna-Dutta-Roy** [comment]
Actually there is one Issue is that protect yourself section I added it as a normal steps. But you can add separate page in the learn more button and link to it.
